version: '3.8'

services:
    gateway_database:
        container_name: gateway_database
        build:
            context: gateway/docker/database
        environment:
            - MYSQL_DATABASE=${GATEWAY_DATABASE_NAME}
            - MYSQL_USER=${GATEWAY_DATABASE_USER}
            - MYSQL_PASSWORD=${GATEWAY_DATABASE_PASSWORD}
            - MYSQL_ROOT_PASSWORD=${GATEWAY_DATABASE_ROOT_PASSWORD}
        ports:
            - "3335:3306"
        volumes:
            - ./gateway/docker/database/data:/var/lib/mysql

    gateway_app:
        container_name: gateway_app
        build:
            context: gateway/docker/php-fpm
        depends_on:
            - gateway_database
        volumes:
            - ./gateway:/var/www

    gateway_nginx:
        container_name: gateway_nginx
        build:
            context: gateway/docker/nginx
        volumes:
            - ./gateway:/var/www
            - ./gateway/docker/nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./gateway/docker/nginx/sites/:/etc/nginx/sites-available
            - ./gateway/docker/nginx/conf.d/:/etc/nginx/conf.d
            - ./gateway/docker/nginx/logs:/var/log/nginx
        depends_on:
            - gateway_app
        ports:
            - "8080:80"

    authservice_app:
        container_name: authservice_app
        build:
            context: auth/docker/php-fpm
        volumes:
            - ./auth:/var/www

    authservice_nginx:
        container_name: authservice_nginx
        build:
            context: auth/docker/nginx
        volumes:
            - ./auth:/var/www
            - ./auth/docker/nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./auth/docker/nginx/sites/:/etc/nginx/sites-available
            - ./auth/docker/nginx/conf.d/:/etc/nginx/conf.d
            - ./auth/docker/nginx/logs:/var/log/nginx
        depends_on:
            - authservice_app
        ports:
            - "8084:80"

    user_database:
        container_name: user_database
        build:
            context: user/docker/database
        environment:
            - MYSQL_DATABASE=${USER_DATABASE_NAME}
            - MYSQL_USER=${USER_DATABASE_USER}
            - MYSQL_PASSWORD=${USER_DATABASE_PASSWORD}
            - MYSQL_ROOT_PASSWORD=${USER_DATABASE_ROOT_PASSWORD}
        ports:
            - "3334:3306"
        volumes:
            - ./user/docker/database/data:/var/lib/mysql

    user_app:
        container_name: user_app
        build:
            context: user/docker/php-fpm
        depends_on:
            - user_database
        volumes:
            - ./user:/var/www

    user_nginx:
        container_name: user_nginx
        build:
            context: user/docker/nginx
        volumes:
            - ./user:/var/www
            - ./user/docker/nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./user/docker/nginx/sites/:/etc/nginx/sites-available
            - ./user/docker/nginx/conf.d/:/etc/nginx/conf.d
            - ./user/docker/nginx/logs:/var/log/nginx
        depends_on:
            - user_app
        ports:
            - "8083:80"
