version: '3'

services:
    user_database:
        container_name: user_database
        build:
            context: database
        environment:
            - MYSQL_DATABASE=${DATABASE_NAME}
            - MYSQL_USER=${DATABASE_USER}
            - MYSQL_PASSWORD=${DATABASE_PASSWORD}
            - MYSQL_ROOT_PASSWORD=${DATABASE_ROOT_PASSWORD}
        ports:
            - "3334:3306"
        volumes:
            - ./database/data:/var/lib/mysql

    user_app:
        container_name: user_app
        build:
            context: php-fpm
        depends_on:
            - user_database
        volumes:
            - ../:/var/www

    user_nginx:
        container_name: user_nginx
        build:
            context: nginx
        volumes:
            - ../:/var/www
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./nginx/sites/:/etc/nginx/sites-available
            - ./nginx/conf.d/:/etc/nginx/conf.d
            - ./nginx/logs:/var/log/nginx
        depends_on:
            - user_app
        ports:
            - "8083:80"
