version: '3.8'

services:
    authservice_database:
        container_name: authservice_database
        build:
            context: database
        environment:
            - MYSQL_DATABASE=${DATABASE_NAME}
            - MYSQL_USER=${DATABASE_USER}
            - MYSQL_PASSWORD=${DATABASE_PASSWORD}
            - MYSQL_ROOT_PASSWORD=${DATABASE_ROOT_PASSWORD}
        ports:
            - "3335:3306"
        volumes:
            - ./database/data:/var/lib/mysql

    authservice_app:
        container_name: authservice_app
        build:
            context: php-fpm
        volumes:
            - ../:/var/www

    authservice_nginx:
        container_name: authservice_nginx
        build:
            context: nginx
        volumes:
            - ../:/var/www
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./nginx/sites/:/etc/nginx/sites-available
            - ./nginx/conf.d/:/etc/nginx/conf.d
            - ./nginx/logs:/var/log/nginx
        depends_on:
            - authservice_app
        ports:
            - "8084:80"
